<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="8" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-21T17:37:08 IST" name="Suite" finished-at="2024-03-21T17:40:10 IST" duration-ms="181644">
    <groups>
    </groups>
    <test started-at="2024-03-21T17:37:08 IST" name="Submit order" finished-at="2024-03-21T17:38:50 IST" duration-ms="101542">
      <class name="UIAutomation.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:37:09 IST" name="launchApplication" finished-at="2024-03-21T17:37:57 IST" duration-ms="48076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:37:57 IST" name="submitOrder" finished-at="2024-03-21T17:38:16 IST" duration-ms="19080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:38:16 IST" name="tearDown" finished-at="2024-03-21T17:38:16 IST" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:38:16 IST" name="launchApplication" finished-at="2024-03-21T17:38:48 IST" duration-ms="32056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyProductInOrderList()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:38:48 IST" name="verifyProductInOrderList" finished-at="2024-03-21T17:38:50 IST" depends-on-methods="UIAutomation.SubmitOrderTest.submitOrder" duration-ms="1666" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductInOrderList -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.SubmitOrderTest@22356acd]" started-at="2024-03-21T17:38:50 IST" name="tearDown" finished-at="2024-03-21T17:38:50 IST" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- UIAutomation.SubmitOrderTest -->
    </test> <!-- Submit order -->
    <test started-at="2024-03-21T17:37:08 IST" name="Error Validation" finished-at="2024-03-21T17:40:10 IST" duration-ms="181644">
      <class name="UIAutomation.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:37:09 IST" name="launchApplication" finished-at="2024-03-21T17:37:57 IST" duration-ms="48093" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:37:57 IST" name="loginErrorValidation" finished-at="2024-03-21T17:38:00 IST" duration-ms="3030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:38:00 IST" name="tearDown" finished-at="2024-03-21T17:38:01 IST" duration-ms="1577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:38:01 IST" name="launchApplication" finished-at="2024-03-21T17:38:37 IST" duration-ms="35231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="productErrorValidation()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:38:37 IST" name="productErrorValidation" finished-at="2024-03-21T17:38:51 IST" duration-ms="14832" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at UIAutomation.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:38:51 IST" name="tearDown" finished-at="2024-03-21T17:38:52 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:38:52 IST" name="launchApplication" finished-at="2024-03-21T17:39:25 IST" duration-ms="33217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="productErrorValidation()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:39:25 IST" name="productErrorValidation" finished-at="2024-03-21T17:39:39 IST" duration-ms="14061" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at UIAutomation.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:39:39 IST" name="tearDown" finished-at="2024-03-21T17:39:39 IST" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:39:39 IST" name="launchApplication" finished-at="2024-03-21T17:39:56 IST" duration-ms="16276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:39:56 IST" name="productErrorValidation" finished-at="2024-03-21T17:40:10 IST" duration-ms="14016" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at UIAutomation.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UIAutomation.ErrorValidationTest@12ed9db6]" started-at="2024-03-21T17:40:10 IST" name="tearDown" finished-at="2024-03-21T17:40:10 IST" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- UIAutomation.ErrorValidationTest -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
